### ISSUE TITLE
CodeIgniter Integration

### ISSUE THREAD

**Issue by benjaminbowles** [drpitman/PHP-Xero#1]
I'm trying to integrate your library into my CodeIgniter project, and get the following message:

A PHP Error was encountered
Severity: Notice
Message: Trying to get property of non-object
Filename: libraries/xero.php
Line Number: 630

This is the code that is accessing the library:

`include_once "xero.php";
define('XERO_KEY','BLABLA');
define('XERO_SECRET','BLABLA');
$xero = new Xero(XERO_KEY, XERO_SECRET, 'xero_keys/publickey.cer', 'xero_keys/privatekey.pem', 'xml');                      
return $xero->Contacts;`

Keys replaced for security, any help would be greatly appreciated.

**Comment by drpitman** [comment]
This means that the OauthConsumer is not being instantiated. You can see this class from line 343.  It's a pretty basic class, so the only thing I can think of is that you are not running PHP5+ ?  This code requires php5.  If I haven't noted that somewhere else in the README etc. I will correct that now.  If you are running PHP5, please let me know and I'll look further into this.

**Comment by benjaminbowles** [comment]
I'm running PHP5 with no luck...

**Comment by drpitman** [comment]
Sorry for a late response, I haven't been ignoring it, just thinking about what else it could be.  I can't replicate the issue on my servers at all.  Is there any other information you could supply?  Any other errors, a phpinfo output etc.?

**Comment by drpitman** [comment]
Might be (probably am) barking up the wrong tree, but does anyone see an issue with this code (from around line 1208):

class OAuthSignatureMethod_Xero extends OAuthSignatureMethod_RSA_SHA1 {
    protected $public_cert;
    protected $private_key;

```
public function __construct($public_cert, $private_key) {
    $this->public_cert = $public_cert;
    $this->private_key = $private_key;
}

protected function fetch_public_cert(&$request) {
    return file_get_contents( $this->public_cert );
}

protected function fetch_private_cert(&$request) {
    return file_get_contents( $this->private_key );
}
```

}

Perhaps some systems don't like the __construct method there without calling a parent::construct()?   Doesn't cause a problem for me anywhere, and none of the parent classes actually have a __construct, but perhaps this could be a pointer in some vague direction of the problem?  I can't really test this because I'm not having the issue, and can' replicate it at all.

I'll try to make some time to create a proper test suite for this class in the near future (no guarantees!), to help people whose systems choke on this code somewhere.

Thanks.

**Comment by jsjohnstone** [comment]
I may be totally barking up the wrong tree, but I think this may have something to do with the .pem and .cer files (the API keys) - I did something to the files which suddenly fixed the problem. Since then, I've moved the files from one subdomain to another and the issue has magically reappeared.

I don't know what it was that I did to make it work the first time, but I thought I'd point this out just in case it was relevant or pointed anyone in the right direction.

Jamie.

**Comment by jsjohnstone** [comment]
After a lot of playing around and thanks to a friendly coder, we found that it is the two certificate files that cause this error. You need to ensure that you have referred to the files correctly in the initialization statement - if they're in the same folder as the Xero.php file, a great way is:

$xero = new Xero(XERO_KEY, XERO_SECRET, dirname(**FILE**).'/publickey.cer', dirname(**FILE**).'/privatekey.pem', 'json' );

Edit: GitHub is turning the double underscores surrounding "FILE" into bold formatting... so just to clarify, the FILE's are surrounded by double underscores.. i.e. _ _ FILE _ _ (without the spaces).

Also - check the permissions of the certificate files. I'm not sure how high or low they need to be, but a combination of playing with the variables of the $xero initialization and the permissions of the cert files themselves resolved it and got me back up and running!

**Comment by drpitman** [comment]
Hey that's great to hear!

**Comment by bubaphex** [comment]
How did you implement this into codeigniter? did you add it as a helper or library ?

**Comment by wireblue** [comment]
I had the same problem and found it was incorrect file paths to the certificate files causing the problems (same as above).
